#!/bin/bash
set -e

# --- Configuration ---
REPO_URL="https://raw.githubusercontent.com/gbzret4d/firewall-blocklist-updater/main/update-firewall-blocklists.sh"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/usr/local/etc/firewall-blocklist-updater"
SCRIPT_NAME="update-firewall-blocklists.sh"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Firewall Blocklist Updater Installer ===${NC}"

# 1. Check Root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root.${NC}"
   exit 1
fi

# 2. Install Dependencies
echo "-> Installing dependencies..."
if command -v apt-get >/dev/null; then
    apt-get update -qq
    apt-get install -y curl ipset iptables unzip dnsutils iproute2 cron
elif command -v dnf >/dev/null; then
    dnf install -y curl ipset iptables unzip bind-utils iproute
elif command -v yum >/dev/null; then
    yum install -y curl ipset iptables unzip bind-utils iproute
elif command -v zypper >/dev/null; then
    zypper install -y curl ipset iptables unzip bind-utils iproute2
else
    echo -e "${RED}Error: Unsupported package manager. Please install dependencies manually.${NC}"
    exit 1
fi

# 3. Create Directories
echo "-> Creating directories..."
mkdir -p "$CONFIG_DIR/firewall-blocklists"
mkdir -p "$CONFIG_DIR/backups"

# 4. Create Default Config (Cleaned for v8.1)
if [[ ! -f "$CONFIG_DIR/firewall-blocklist-keys.env" ]]; then
    echo "-> Creating default configuration..."
    cat <<EOF > "$CONFIG_DIR/firewall-blocklist-keys.env"
# Firewall Blocklist Configuration
# Generated by install.sh

# --- Geo-Blocking ---
# Use 2-letter ISO codes (e.g. DE AT CH)
WHITELIST_COUNTRIES="DE AT"
BLOCKLIST_COUNTRIES="CN RU KP IR"

# --- DynDNS Whitelist ---
# Allow dynamic IP (e.g., your home IP)
DYNDNS_HOST=""

# --- API Keys ---
# Get free key from: https://www.abuseipdb.com/ account/api
ABUSEIPDB_API_KEY=""

# --- Telegram Notifications ---
# Get Token from @BotFather, Chat ID from @userinfobot
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""
EOF
    chmod 600 "$CONFIG_DIR/firewall-blocklist-keys.env"
else
    echo "-> Config file already exists. Skipping creation."
fi

# 5. Download Script
echo "-> Downloading latest script version..."
curl -sfL "$REPO_URL" -o "$INSTALL_DIR/$SCRIPT_NAME"
chmod +x "$INSTALL_DIR/$SCRIPT_NAME"

# 6. Setup Systemd Timer
echo "-> Setting up Systemd Timer (Daily update)..."

cat <<EOF > /etc/systemd/system/firewall-blocklist-updater.service
[Unit]
Description=Firewall Blocklist Updater
After=network.target network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=$INSTALL_DIR/$SCRIPT_NAME
EOF

cat <<EOF > /etc/systemd/system/firewall-blocklist-updater.timer
[Unit]
Description=Run Firewall Blocklist Updater Daily

[Timer]
OnCalendar=daily
RandomizedDelaySec=3600
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now firewall-blocklist-updater.timer

echo -e "${GREEN}=== Installation Complete! ===${NC}"
echo ""
echo "Next steps:"
echo "1. Edit config: nano $CONFIG_DIR/firewall-blocklist-keys.env"
echo "2. Setup Sensors: $SCRIPT_NAME --configure"
echo "3. Run manually:  $SCRIPT_NAME"
echo ""